package rpcprotocol;

public enum RequestType {
    LOGIN,LOGOUT,GET_CHARITABLE_CASES,SAVE_DONATION,GET_DONORS_BY_NAME,GET_DONOR_BY_FULL_NAME,SAVE_DONOR,
    GET_DONOR_ID,GET_DONOR,GET_CHARITABLE_CASE;
}
